version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app.py
    volumes:
      - .:/code
  redis:
    container_name: redis
    image: "redis:alpine"
  portcast_db:
    container_name: portcast_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: local
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
