CREATE TABLE IF NOT EXISTS content (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP,
  body TEXT
);

CREATE INDEX fts_body ON content USING gin(to_tsvector('english', body));